import Head from "next/head";

import { Divider } from "@chakra-ui/react";

// components
import HeroSection from "../components/HeroSection";
import Slider from "../components/Slider";
import Brands from "../components/Brands";
import InfoSection from "../components/InfoSection";
import Newsletter from "../components/Newsletter";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Black Steel | Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroSection />
      <Slider />
      <Divider />
      <Brands />
      <InfoSection />
      <Divider />

      <Newsletter />
    </div>
  );
}
